### ISSUE TITLE
The difference of implementation 

### ISSUE THREAD

**Issue by Joshua1225** [GostInShell/PaRI-Conv#1]
Hi. Thanks for sharing codes. Your work is excellent and significant for inspiring others.

However, I tried to reproduce the performance of your method, Pari-Conv,  and only got 92.0% twice on MoldelNet40.
And the codes of Pari-conv seem to be different from that provided in the paper. The dynamic kernel shall be a k*C*C matrix and operated with matrix multiplication. But in the model.py, it's k*C and used with Hadamard product. 
Is it the reason for low performance？ Please check Lines 107-130 in model.py.

**Comment by GostInShell** [comment]
Thanks for liking our work! Your words inspire us too!

Let me clarify the implementation first. It is actually the same as the description in the paper. But we do a little trick for simplicity.
Our dynamic kernel is factorized into a diagonal matrix and a basis matrix. We implementat the basis matrix as a linear layer `self.basis_matrix()`, and the diagonal matrix as a vector `self.dynamic_kernel(APPF)`. 

Note that **A matrix multipilcation with a diagonal matrix equals to the Hadamard product with the diagonal vector.** So they are actually the same.

For the performance, the current version has some differeces with the initial version in the pre-processing steps. I'll check the code and update it in a few days.
